name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run build script
        shell: cmd
        run: |
          echo Running build.bat...
          call build.bat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: W10Fonts-EXE
          path: |
            *.exe
          if-no-files-found: error
