name: Build

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run build script
        shell: cmd
        run: |
          echo Running build.bat...
          call build.bat

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: W10Fonts-installer
          path: |
            *.exe
          if-no-files-found: error
